--[[
Azeroth Chronicle - Summaries.lua

Reads recaps generated by the companion out of AzerothChronicleSummariesDB,
a global written by a separate, generated addon (AzerothChronicleSummaries).

This is a one-way bridge, companion to game, and it exists because of a real
constraint: the addon sandbox cannot make network calls, and SavedVariables
is the wrong channel for the other direction because the client owns that
file and rewrites it wholesale on every reload, discarding anything the
companion wrote there in between. A second addon whose Lua *is* the data is
the one channel that actually survives: the client loads it as code at
login or /reload and never touches it again until the next publish.

That is also this feature's real limitation, stated rather than hidden: a
recap can only appear after a login or reload, never mid-session, because
that is the only time the client reads addon files at all.

Nothing here is captured data, and nothing here is written back. Reads are
defensive throughout, because this table comes from outside code this addon
does not control, generated by a separate program that could in principle
be interrupted mid-write or produce something malformed.
]]

local ADDON_NAME = ...

AC = AC or {}
AC.Summaries = {}

-- Every recap for the character currently logged in, newest first. Returns
-- an empty table, never nil and never an error, whether the generated addon
-- is absent, disabled, empty, or malformed - a missing recap should look
-- exactly like "none yet" everywhere that reads this.
function AC.Summaries.ForCurrentCharacter()
    local ok, result = pcall(function()
        local db = _G.AzerothChronicleSummariesDB
        if type(db) ~= "table" then
            return {}
        end

        local guid = UnitGUID("player")
        local entries = guid and db[guid]
        if type(entries) ~= "table" then
            return {}
        end

        local list = {}
        for _, entry in ipairs(entries) do
            if type(entry) == "table" and entry.text then
                list[#list + 1] = entry
            end
        end

        table.sort(list, function(a, b)
            return (a.windowEnd or 0) > (b.windowEnd or 0)
        end)
        return list
    end)

    if ok then
        return result
    end
    if AC.Debug and AC.Debug.Error then
        AC.Debug.Error("Summaries.ForCurrentCharacter", result)
    end
    return {}
end

-- Whether the generated addon is present at all, so the pane can tell "you
-- have not generated a recap yet" apart from "that addon is not installed
-- or enabled", which need different instructions to fix.
function AC.Summaries.IsAddonPresent()
    return type(_G.AzerothChronicleSummariesDB) == "table"
end
