--[[
Azeroth Chronicle - Summaries.lua

Reads recaps generated by the companion out of AzerothChronicleSummariesDB,
a global written by a separate, generated addon (AzerothChronicleSummaries).

This is a one-way bridge, companion to game, and it exists because of a real
constraint: the addon sandbox cannot make network calls, and SavedVariables
is the wrong channel for the other direction because the client owns that
file and rewrites it wholesale on every reload, discarding anything the
companion wrote there in between. A second addon whose Lua *is* the data is
the one channel that actually survives: the client loads it as code at
login or /reload and never touches it again until the next publish.

That is also this feature's real limitation, stated rather than hidden: a
recap can only appear after a login or reload, never mid-session, because
that is the only time the client reads addon files at all.

Nothing here is captured data, and nothing here is written back. Reads are
defensive throughout, because this table comes from outside code this addon
does not control, generated by a separate program that could in principle
be interrupted mid-write or produce something malformed.
]]

local ADDON_NAME = ...

AC = AC or {}
AC.Summaries = {}

-- Every generated summary for the character currently logged in, of any
-- kind, unsorted. Both recaps and chapters read from the same published
-- table (see publish.py), and want different filters and different sort
-- orders, so this does neither and leaves both to its callers.
local function AllEntries()
    local db = _G.AzerothChronicleSummariesDB
    if type(db) ~= "table" then
        return {}
    end

    local guid = UnitGUID("player")
    local entries = guid and db[guid]
    if type(entries) ~= "table" then
        return {}
    end

    local list = {}
    for _, entry in ipairs(entries) do
        if type(entry) == "table" and entry.text then
            list[#list + 1] = entry
        end
    end
    return list
end

-- Runs any reader defensively: a missing, disabled, or malformed generated
-- addon should look exactly like "nothing yet" everywhere this is read,
-- never an error, since this table comes from outside code the addon does
-- not control.
local function SafeRead(fn)
    local ok, result = pcall(fn)
    if ok then
        return result
    end
    if AC.Debug and AC.Debug.Error then
        AC.Debug.Error("Summaries", result)
    end
    return {}
end

-- Session recaps, newest first - "what did I just do."
function AC.Summaries.ForCurrentCharacter()
    return SafeRead(function()
        local list = {}
        for _, entry in ipairs(AllEntries()) do
            if entry.kind == "session_recap" or entry.kind == nil then
                list[#list + 1] = entry
            end
        end
        table.sort(list, function(a, b)
            return (a.windowEnd or 0) > (b.windowEnd or 0)
        end)
        return list
    end)
end

-- Zone chapters, oldest first - "the story so far, from the beginning."
-- Ordered by windowStart, which the companion sets to the zone's earliest
-- recorded activity, so chapter order matches the order the character
-- actually visited these places rather than when each chapter was last
-- (re)written.
function AC.Summaries.ChaptersForCurrentCharacter()
    return SafeRead(function()
        local list = {}
        for _, entry in ipairs(AllEntries()) do
            if entry.kind == "zone_chapter" then
                list[#list + 1] = entry
            end
        end
        table.sort(list, function(a, b)
            return (a.windowStart or 0) < (b.windowStart or 0)
        end)
        return list
    end)
end

-- Whether the generated addon is present at all, so the pane can tell "you
-- have not generated a recap yet" apart from "that addon is not installed
-- or enabled", which need different instructions to fix.
function AC.Summaries.IsAddonPresent()
    return type(_G.AzerothChronicleSummariesDB) == "table"
end
