"""Publish generated recaps into the game as a second, generated addon.

The addon sandbox cannot make network calls or read arbitrary files, and
SavedVariables is the wrong bridge for this: the client owns that file and
rewrites it wholesale from its own memory on every reload, so anything the
companion wrote there would just be overwritten. See development-spec.md
section 4, "SavedVariables are not real-time IPC".

The bridge that actually works is a second addon whose Lua *is* the data.
The client loads any enabled addon's files as code at login or /reload,
never overwrites them, and never touches them again until the next publish.
That is also this feature's real limitation: a recap only appears after a
login or reload, never mid-session, because that is the only time the
client reads addon files at all.

This is generated content, not a player annotation and not a captured
observation, so it lives in its own addon, entirely separate from both the
event journal and the hand-authored threads. Nothing here is ever read back
by the companion; it is one-way, companion to game.
"""
import re
import time
from pathlib import Path

from . import discovery

ADDON_NAME = 'AzerothChronicleSummaries'
DATA_FILE = 'Summaries.lua'
TOC_FILE = ADDON_NAME + '.toc'

# Used only if the main addon's own TOC cannot be found to read the real
# number from. Keeping one hardcoded fallback here, clearly marked, beats
# silently duplicating the number in two places that could drift apart.
FALLBACK_INTERFACE_VERSION = '11509'

_INTERFACE_LINE = re.compile(r'^##\s*Interface:\s*(\S+)', re.MULTILINE)


def _lua_long_bracket(text):
    """Wrap text in a Lua long-bracket string, escaping only what must be.

    A long bracket ([[...]]) needs no escaping for quotes or backslashes,
    which matters here because recap prose is arbitrary model output and
    quoting every character would make the generated file unreadable. The
    only real risk is the text itself containing a closing sequence; Lua's
    own answer is to widen the bracket with `=` signs until the closer no
    longer appears, which is what this does rather than assuming ']]' is
    safe.
    """
    text = text or ''
    level = 0
    while (']' + '=' * level + ']') in text:
        level += 1
    eq = '=' * level

    # A long bracket string silently drops one immediate leading newline.
    # Prefixing a blank comment line neutralizes that quirk so the text is
    # reproduced exactly rather than losing a leading blank line sometimes
    # and not others.
    return '[%s[\n%s]%s]' % (eq, text, eq)


def _lua_string(value):
    """A normal quoted Lua string, for short fields like ids and model names."""
    if value is None:
        return '""'
    escaped = (str(value)
               .replace('\\', '\\\\')
               .replace('"', '\\"')
               .replace('\n', '\\n'))
    return '"%s"' % escaped


def _lua_number(value):
    return str(value) if value is not None else 'nil'


def read_interface_version(addons_dir, addon_name='AzerothChronicle'):
    """Read the real interface number from the main addon's own TOC.

    Keeps the two addons' interface numbers from silently drifting apart:
    there is exactly one place this number is authored (the main addon's
    TOC), and everything else reads it rather than hardcoding a second copy.
    """
    toc_path = Path(addons_dir) / addon_name / (addon_name + '.toc')
    if not toc_path.is_file():
        return None
    match = _INTERFACE_LINE.search(toc_path.read_text(encoding='utf-8'))
    return match.group(1) if match else None


def build_toc(interface_version):
    # Each ## directive must stay on one physical line: the client parses
    # them independently, and a wrapped Notes value would put a colon-less
    # second line where a key:value pair is expected.
    return (
        '## Interface: %s\n'
        '## Title: Azeroth Chronicle Summaries\n'
        '## Notes: Generated recaps for Azeroth Chronicle. Rewritten on every publish.\n'
        '## Version: 0.1.0\n\n'
        '%s\n' % (interface_version, DATA_FILE))


def build_data_file(rows_by_character, generated_at=None):
    """Render every stored summary as one Lua assignment, grouped by character.

    Grouped by character GUID rather than flattened, so the addon-side
    lookup for "recaps for the character currently logged in" is a single
    table access rather than a scan, and so one player's history staying
    separate from another's needs no extra code to enforce.
    """
    generated_at = generated_at or int(time.time())
    lines = [
        '-- Generated by the Azeroth Chronicle companion. Do not edit; this',
        '-- file is overwritten on every publish. The companion\'s SQLite',
        '-- summaries table is the source of truth, not this file.',
        '-- Generated at %d.' % generated_at,
        '',
        'AzerothChronicleSummariesDB = {',
    ]

    for character_id in sorted(rows_by_character):
        lines.append('[%s] = {' % _lua_string(character_id))
        rows = sorted(rows_by_character[character_id],
                      key=lambda r: r['window_end'] or 0, reverse=True)
        for row in rows:
            lines.append('{')
            lines.append('["id"] = %s,' % _lua_string(row['summary_id']))
            lines.append('["kind"] = %s,' % _lua_string(row['kind']))
            lines.append('["windowStart"] = %s,' % _lua_number(row['window_start']))
            lines.append('["windowEnd"] = %s,' % _lua_number(row['window_end']))
            lines.append('["model"] = %s,' % _lua_string(row['model']))
            lines.append('["createdAt"] = %s,' % _lua_number(row['created_at']))
            lines.append('["text"] = %s,' % _lua_long_bracket(row['text']))
            lines.append('},')
        lines.append('},')

    lines.append('}')
    return '\n'.join(lines) + '\n'


def _atomic_write(path, text):
    """Write via a temp file plus replace, so the client never sees a
    half-written file mid-publish. A partial Lua file that happens to load
    is invisible corruption; one that fails to parse breaks the whole addon
    until the next successful publish overwrites it."""
    path = Path(path)
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_text(text, encoding='utf-8')
    tmp.replace(path)


def publish(conn, wow_path=None, addon_name='AzerothChronicle'):
    """Write every stored summary out as the generated addon.

    Returns the list of AddOns directories written to, or an empty list if
    the main addon could not be found anywhere to publish alongside.
    """
    targets = discovery.find_addon_installations(wow_path, addon_name)
    if not targets:
        return []

    rows_by_character = {}
    for row in conn.execute(
            'SELECT summary_id, character_id, kind, window_start, window_end,'
            '       model, created_at, text FROM summaries'
            ' WHERE character_id IS NOT NULL'):
        rows_by_character.setdefault(row['character_id'], []).append(row)

    for addons_dir in targets:
        interface_version = (read_interface_version(addons_dir, addon_name)
                             or FALLBACK_INTERFACE_VERSION)

        addon_dir = addons_dir / ADDON_NAME
        addon_dir.mkdir(parents=True, exist_ok=True)

        _atomic_write(addon_dir / TOC_FILE, build_toc(interface_version))
        _atomic_write(addon_dir / DATA_FILE, build_data_file(rows_by_character))

    return targets
